# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-13 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Football',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_time', models.CharField(default='', max_length=16)),
                ('timer', models.CharField(default='', max_length=16)),
                ('team_home', models.CharField(default='', max_length=32)),
                ('hcard', models.CharField(default='', max_length=8)),
                ('score', models.CharField(default='', max_length=32)),
                ('team_away', models.CharField(default='', max_length=32)),
                ('acard', models.CharField(default='', max_length=8)),
                ('squad', models.CharField(default='', max_length=32)),
            ],
            options={
                'db_table': 'Football',
            },
        ),
    ]
