# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roberto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(default='', max_length=32)),
            ],
            options={
                'db_table': 'Country',
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_link', models.CharField(default='', max_length=16)),
                ('caption', models.CharField(default='', max_length=64)),
                ('country', models.CharField(default='', max_length=64)),
            ],
            options={
                'db_table': 'League',
            },
        ),
        migrations.RenameField(
            model_name='football',
            old_name='squad',
            new_name='part_top',
        ),
        migrations.RenameField(
            model_name='football',
            old_name='acard',
            new_name='racard',
        ),
        migrations.RenameField(
            model_name='football',
            old_name='hcard',
            new_name='rhcard',
        ),
    ]
