# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roberto', '0002_auto_20180519_1707'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='country',
            table='country',
        ),
        migrations.AlterModelTable(
            name='football',
            table='soccer',
        ),
        migrations.AlterModelTable(
            name='league',
            table='league',
        ),
    ]
