# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roberto', '0003_auto_20180519_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='football',
            name='html_link',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='football',
            name='league',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='roberto.League'),
        ),
    ]
