# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roberto', '0004_auto_20180519_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_time', models.CharField(default='', max_length=16)),
                ('timer', models.CharField(default='', max_length=16)),
                ('team_home', models.CharField(default='', max_length=32)),
                ('rhcard', models.CharField(default='', max_length=8)),
                ('score', models.CharField(default='', max_length=32)),
                ('team_away', models.CharField(default='', max_length=32)),
                ('racard', models.CharField(default='', max_length=8)),
                ('part_top', models.CharField(default='', max_length=32)),
                ('html_link', models.CharField(default='', max_length=16)),
            ],
            options={
                'db_table': 'event_game',
            },
        ),
    ]
