# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-20 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roberto', '0005_eventgame'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(default='', max_length=32)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roberto.EventGame')),
            ],
            options={
                'db_table': 'event_params',
            },
        ),
    ]
