# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-20 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roberto', '0006_eventparams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventparams',
            name='event_id',
        ),
        migrations.AddField(
            model_name='eventparams',
            name='html_link',
            field=models.CharField(default='', max_length=16),
        ),
    ]
