# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-20 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('roberto', '0007_auto_20180520_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgame',
            name='event_type',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='eventgame',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventparams',
            name='event_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='roberto.EventGame'),
            preserve_default=False,
        ),
    ]
