# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roberto', '0008_auto_20180520_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgame',
            name='live_p1',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='eventgame',
            name='live_p2',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='eventgame',
            name='live_x',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='eventgame',
            name='pre_p1',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='eventgame',
            name='pre_p2',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='eventgame',
            name='pre_x',
            field=models.CharField(default='', max_length=8),
        ),
    ]
