# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roberto', '0009_auto_20180526_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgame',
            name='dog',
            field=models.CharField(default='', max_length=2),
        ),
    ]
